version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: super-secret-key
      JWT_SECRET_KEY: jwt-secret-key
